# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontdash.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 605)
        MainWindow.setStyleSheet("    background: #FEF9FF;\n"
"border: 1px dashed darkblue;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setObjectName("treeWidget")
        self.gridLayout.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    color: #444444;\n"
"    background: #F3F3F3;\n"
"    border: 1px #DADADA solid;\n"
"    padding: 5px 10px;\n"
"    border-radius: 2px;\n"
"    font-weight: bold;\n"
"    font-size: 9pt;\n"
"    outline: none;\n"
"}\n"
"\n"
"button:hover {\n"
"    border: 1px #C6C6C6 solid;\n"
"    box-shadow: 1px 1px 1px #EAEAEA;\n"
"    color: #333333;\n"
"    background: #F7F7F7;\n"
"}\n"
"\n"
"QPushButton:active {\n"
"    box-shadow: inset 1px 1px 1px #DFDFDF;   \n"
"}\n"
"\n"
"/* Blue button as seen on translate.google.com*/\n"
"QPushButton:blue {\n"
"    color: white;\n"
"    background: #4C8FFB;\n"
"    border: 1px #3079ED solid;\n"
"    box-shadow: inset 0 1px 0 #80B0FB;\n"
"}\n"
"\n"
"QPushButton:blue:hover {\n"
"    border: 1px #2F5BB7 solid;\n"
"    box-shadow: 0 1px 1px #EAEAEA, inset 0 1px 0 #5A94F1;\n"
"    background: #3F83F1;\n"
"}\n"
"\n"
"QPushButton:blue:active {\n"
"    box-shadow: inset 0 2px 5px #2370FE;   \n"
"}\n"
"\n"
"/* Orange button as seen on blogger.com*/\n"
"QPushButton:orange {\n"
"    color: white;\n"
"    border: 1px solid #FB8F3D; \n"
"    background: -webkit-linear-gradient(top, #FDA251, #FB8F3D);\n"
"    background: -moz-linear-gradient(top, #FDA251, #FB8F3D);\n"
"    background: -ms-linear-gradient(top, #FDA251, #FB8F3D);\n"
"}\n"
"\n"
"QPushButton:orange:hover {\n"
"    border: 1px solid #EB5200;\n"
"    background: -webkit-linear-gradient(top, #FD924C, #F9760B); \n"
"    background: -moz-linear-gradient(top, #FD924C, #F9760B); \n"
"    background: -ms-linear-gradient(top, #FD924C, #F9760B); \n"
"    box-shadow: 0 1px #EFEFEF;\n"
"}\n"
"\n"
"QPushButton:orange:active {\n"
"    box-shadow: inset 0 1px 1px rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"/* Red Google Button as seen on drive.google.com */\n"
"QPushButton:red {\n"
"    background: -webkit-linear-gradient(top, #DD4B39, #D14836); \n"
"    background: -moz-linear-gradient(top, #DD4B39, #D14836); \n"
"    background: -ms-linear-gradient(top, #DD4B39, #D14836); \n"
"    border: 1px solid #DD4B39;\n"
"    color: white;\n"
"    text-shadow: 0 1px 0 #C04131;\n"
"}\n"
"\n"
"QPushButton:red:hover {\n"
"     background: -webkit-linear-gradient(top, #DD4B39, #C53727);\n"
"     background: -moz-linear-gradient(top, #DD4B39, #C53727);\n"
"     background: -ms-linear-gradient(top, #DD4B39, #C53727);\n"
"     border: 1px solid #AF301F;\n"
"}\n"
"\n"
"QPushButton:red:active {\n"
"     box-shadow: inset 0 1px 1px rgba(0,0,0,0.2);\n"
"    background: -webkit-linear-gradient(top, #D74736, #AD2719);\n"
"    background: -moz-linear-gradient(top, #D74736, #AD2719);\n"
"    background: -ms-linear-gradient(top, #D74736, #AD2719);\n"
"}\n"
"\n"
"\n"
"\n"
"/*=======================================*/\n"
"\n"
"body {\n"
"    margin: 50px;\n"
"}\n"
"\n"
"h1 {\n"
"    font: 150%/150% \'Freckle Face\', cursive;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 4, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    color: #444444;\n"
"    background: #F3F3F3;\n"
"    border: 1px #DADADA solid;\n"
"    padding: 5px 10px;\n"
"    border-radius: 2px;\n"
"    font-weight: bold;\n"
"    font-size: 9pt;\n"
"    outline: none;\n"
"}\n"
"\n"
"button:hover {\n"
"    border: 1px #C6C6C6 solid;\n"
"    box-shadow: 1px 1px 1px #EAEAEA;\n"
"    color: #333333;\n"
"    background: #F7F7F7;\n"
"}\n"
"\n"
"QPushButton:active {\n"
"    box-shadow: inset 1px 1px 1px #DFDFDF;   \n"
"}\n"
"\n"
"/* Blue button as seen on translate.google.com*/\n"
"QPushButton:blue {\n"
"    color: white;\n"
"    background: #4C8FFB;\n"
"    border: 1px #3079ED solid;\n"
"    box-shadow: inset 0 1px 0 #80B0FB;\n"
"}\n"
"\n"
"QPushButton:blue:hover {\n"
"    border: 1px #2F5BB7 solid;\n"
"    box-shadow: 0 1px 1px #EAEAEA, inset 0 1px 0 #5A94F1;\n"
"    background: #3F83F1;\n"
"}\n"
"\n"
"QPushButton:blue:active {\n"
"    box-shadow: inset 0 2px 5px #2370FE;   \n"
"}\n"
"\n"
"/* Orange button as seen on blogger.com*/\n"
"QPushButton:orange {\n"
"    color: white;\n"
"    border: 1px solid #FB8F3D; \n"
"    background: -webkit-linear-gradient(top, #FDA251, #FB8F3D);\n"
"    background: -moz-linear-gradient(top, #FDA251, #FB8F3D);\n"
"    background: -ms-linear-gradient(top, #FDA251, #FB8F3D);\n"
"}\n"
"\n"
"QPushButton:orange:hover {\n"
"    border: 1px solid #EB5200;\n"
"    background: -webkit-linear-gradient(top, #FD924C, #F9760B); \n"
"    background: -moz-linear-gradient(top, #FD924C, #F9760B); \n"
"    background: -ms-linear-gradient(top, #FD924C, #F9760B); \n"
"    box-shadow: 0 1px #EFEFEF;\n"
"}\n"
"\n"
"QPushButton:orange:active {\n"
"    box-shadow: inset 0 1px 1px rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"/* Red Google Button as seen on drive.google.com */\n"
"QPushButton:red {\n"
"    background: -webkit-linear-gradient(top, #DD4B39, #D14836); \n"
"    background: -moz-linear-gradient(top, #DD4B39, #D14836); \n"
"    background: -ms-linear-gradient(top, #DD4B39, #D14836); \n"
"    border: 1px solid #DD4B39;\n"
"    color: white;\n"
"    text-shadow: 0 1px 0 #C04131;\n"
"}\n"
"\n"
"QPushButton:red:hover {\n"
"     background: -webkit-linear-gradient(top, #DD4B39, #C53727);\n"
"     background: -moz-linear-gradient(top, #DD4B39, #C53727);\n"
"     background: -ms-linear-gradient(top, #DD4B39, #C53727);\n"
"     border: 1px solid #AF301F;\n"
"}\n"
"\n"
"QPushButton:red:active {\n"
"     box-shadow: inset 0 1px 1px rgba(0,0,0,0.2);\n"
"    background: -webkit-linear-gradient(top, #D74736, #AD2719);\n"
"    background: -moz-linear-gradient(top, #D74736, #AD2719);\n"
"    background: -ms-linear-gradient(top, #D74736, #AD2719);\n"
"}\n"
"\n"
"\n"
"\n"
"/*=======================================*/\n"
"\n"
"body {\n"
"    margin: 50px;\n"
"}\n"
"\n"
"h1 {\n"
"    font: 150%/150% \'Freckle Face\', cursive;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    color: #444444;\n"
"    background: #F3F3F3;\n"
"    border: 1px #DADADA solid;\n"
"    padding: 5px 10px;\n"
"    border-radius: 2px;\n"
"    font-weight: bold;\n"
"    font-size: 9pt;\n"
"    outline: none;\n"
"}\n"
"\n"
"button:hover {\n"
"    border: 1px #C6C6C6 solid;\n"
"    box-shadow: 1px 1px 1px #EAEAEA;\n"
"    color: #333333;\n"
"    background: #F7F7F7;\n"
"}\n"
"\n"
"QPushButton:active {\n"
"    box-shadow: inset 1px 1px 1px #DFDFDF;   \n"
"}\n"
"\n"
"/* Blue button as seen on translate.google.com*/\n"
"QPushButton:blue {\n"
"    color: white;\n"
"    background: #4C8FFB;\n"
"    border: 1px #3079ED solid;\n"
"    box-shadow: inset 0 1px 0 #80B0FB;\n"
"}\n"
"\n"
"QPushButton:blue:hover {\n"
"    border: 1px #2F5BB7 solid;\n"
"    box-shadow: 0 1px 1px #EAEAEA, inset 0 1px 0 #5A94F1;\n"
"    background: #3F83F1;\n"
"}\n"
"\n"
"QPushButton:blue:active {\n"
"    box-shadow: inset 0 2px 5px #2370FE;   \n"
"}\n"
"\n"
"/* Orange button as seen on blogger.com*/\n"
"QPushButton:orange {\n"
"    color: white;\n"
"    border: 1px solid #FB8F3D; \n"
"    background: -webkit-linear-gradient(top, #FDA251, #FB8F3D);\n"
"    background: -moz-linear-gradient(top, #FDA251, #FB8F3D);\n"
"    background: -ms-linear-gradient(top, #FDA251, #FB8F3D);\n"
"}\n"
"\n"
"QPushButton:orange:hover {\n"
"    border: 1px solid #EB5200;\n"
"    background: -webkit-linear-gradient(top, #FD924C, #F9760B); \n"
"    background: -moz-linear-gradient(top, #FD924C, #F9760B); \n"
"    background: -ms-linear-gradient(top, #FD924C, #F9760B); \n"
"    box-shadow: 0 1px #EFEFEF;\n"
"}\n"
"\n"
"QPushButton:orange:active {\n"
"    box-shadow: inset 0 1px 1px rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"/* Red Google Button as seen on drive.google.com */\n"
"QPushButton:red {\n"
"    background: -webkit-linear-gradient(top, #DD4B39, #D14836); \n"
"    background: -moz-linear-gradient(top, #DD4B39, #D14836); \n"
"    background: -ms-linear-gradient(top, #DD4B39, #D14836); \n"
"    border: 1px solid #DD4B39;\n"
"    color: white;\n"
"    text-shadow: 0 1px 0 #C04131;\n"
"}\n"
"\n"
"QPushButton:red:hover {\n"
"     background: -webkit-linear-gradient(top, #DD4B39, #C53727);\n"
"     background: -moz-linear-gradient(top, #DD4B39, #C53727);\n"
"     background: -ms-linear-gradient(top, #DD4B39, #C53727);\n"
"     border: 1px solid #AF301F;\n"
"}\n"
"\n"
"QPushButton:red:active {\n"
"     box-shadow: inset 0 1px 1px rgba(0,0,0,0.2);\n"
"    background: -webkit-linear-gradient(top, #D74736, #AD2719);\n"
"    background: -moz-linear-gradient(top, #D74736, #AD2719);\n"
"    background: -ms-linear-gradient(top, #D74736, #AD2719);\n"
"}\n"
"\n"
"\n"
"\n"
"/*=======================================*/\n"
"\n"
"body {\n"
"    margin: 50px;\n"
"}\n"
"\n"
"h1 {\n"
"    font: 150%/150% \'Freckle Face\', cursive;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 5, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    color: #444444;\n"
"    background: #F3F3F3;\n"
"    border: 1px #DADADA solid;\n"
"    padding: 5px 10px;\n"
"    border-radius: 2px;\n"
"    font-weight: bold;\n"
"    font-size: 9pt;\n"
"    outline: none;\n"
"}\n"
"\n"
"button:hover {\n"
"    border: 1px #C6C6C6 solid;\n"
"    box-shadow: 1px 1px 1px #EAEAEA;\n"
"    color: #333333;\n"
"    background: #F7F7F7;\n"
"}\n"
"\n"
"QPushButton:active {\n"
"    box-shadow: inset 1px 1px 1px #DFDFDF;   \n"
"}\n"
"\n"
"/* Blue button as seen on translate.google.com*/\n"
"QPushButton:blue {\n"
"    color: white;\n"
"    background: #4C8FFB;\n"
"    border: 1px #3079ED solid;\n"
"    box-shadow: inset 0 1px 0 #80B0FB;\n"
"}\n"
"\n"
"QPushButton:blue:hover {\n"
"    border: 1px #2F5BB7 solid;\n"
"    box-shadow: 0 1px 1px #EAEAEA, inset 0 1px 0 #5A94F1;\n"
"    background: #3F83F1;\n"
"}\n"
"\n"
"QPushButton:blue:active {\n"
"    box-shadow: inset 0 2px 5px #2370FE;   \n"
"}\n"
"\n"
"/* Orange button as seen on blogger.com*/\n"
"QPushButton:orange {\n"
"    color: white;\n"
"    border: 1px solid #FB8F3D; \n"
"    background: -webkit-linear-gradient(top, #FDA251, #FB8F3D);\n"
"    background: -moz-linear-gradient(top, #FDA251, #FB8F3D);\n"
"    background: -ms-linear-gradient(top, #FDA251, #FB8F3D);\n"
"}\n"
"\n"
"QPushButton:orange:hover {\n"
"    border: 1px solid #EB5200;\n"
"    background: -webkit-linear-gradient(top, #FD924C, #F9760B); \n"
"    background: -moz-linear-gradient(top, #FD924C, #F9760B); \n"
"    background: -ms-linear-gradient(top, #FD924C, #F9760B); \n"
"    box-shadow: 0 1px #EFEFEF;\n"
"}\n"
"\n"
"QPushButton:orange:active {\n"
"    box-shadow: inset 0 1px 1px rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"/* Red Google Button as seen on drive.google.com */\n"
"QPushButton:red {\n"
"    background: -webkit-linear-gradient(top, #DD4B39, #D14836); \n"
"    background: -moz-linear-gradient(top, #DD4B39, #D14836); \n"
"    background: -ms-linear-gradient(top, #DD4B39, #D14836); \n"
"    border: 1px solid #DD4B39;\n"
"    color: white;\n"
"    text-shadow: 0 1px 0 #C04131;\n"
"}\n"
"\n"
"QPushButton:red:hover {\n"
"     background: -webkit-linear-gradient(top, #DD4B39, #C53727);\n"
"     background: -moz-linear-gradient(top, #DD4B39, #C53727);\n"
"     background: -ms-linear-gradient(top, #DD4B39, #C53727);\n"
"     border: 1px solid #AF301F;\n"
"}\n"
"\n"
"QPushButton:red:active {\n"
"     box-shadow: inset 0 1px 1px rgba(0,0,0,0.2);\n"
"    background: -webkit-linear-gradient(top, #D74736, #AD2719);\n"
"    background: -moz-linear-gradient(top, #D74736, #AD2719);\n"
"    background: -ms-linear-gradient(top, #D74736, #AD2719);\n"
"}\n"
"\n"
"\n"
"\n"
"/*=======================================*/\n"
"\n"
"body {\n"
"    margin: 50px;\n"
"}\n"
"\n"
"h1 {\n"
"    font: 150%/150% \'Freckle Face\', cursive;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: #444444;\n"
"    background: #F3F3F3;\n"
"    border: 1px #DADADA solid;\n"
"    padding: 5px 10px;\n"
"    border-radius: 2px;\n"
"    font-weight: bold;\n"
"    font-size: 9pt;\n"
"    outline: none;\n"
"}\n"
"\n"
"button:hover {\n"
"    border: 1px #C6C6C6 solid;\n"
"    box-shadow: 1px 1px 1px #EAEAEA;\n"
"    color: #333333;\n"
"    background: #F7F7F7;\n"
"}\n"
"\n"
"QPushButton:active {\n"
"    box-shadow: inset 1px 1px 1px #DFDFDF;   \n"
"}\n"
"\n"
"/* Blue button as seen on translate.google.com*/\n"
"QPushButton:blue {\n"
"    color: white;\n"
"    background: #4C8FFB;\n"
"    border: 1px #3079ED solid;\n"
"    box-shadow: inset 0 1px 0 #80B0FB;\n"
"}\n"
"\n"
"QPushButton:blue:hover {\n"
"    border: 1px #2F5BB7 solid;\n"
"    box-shadow: 0 1px 1px #EAEAEA, inset 0 1px 0 #5A94F1;\n"
"    background: #3F83F1;\n"
"}\n"
"\n"
"QPushButton:blue:active {\n"
"    box-shadow: inset 0 2px 5px #2370FE;   \n"
"}\n"
"\n"
"/* Orange button as seen on blogger.com*/\n"
"QPushButton:orange {\n"
"    color: white;\n"
"    border: 1px solid #FB8F3D; \n"
"    background: -webkit-linear-gradient(top, #FDA251, #FB8F3D);\n"
"    background: -moz-linear-gradient(top, #FDA251, #FB8F3D);\n"
"    background: -ms-linear-gradient(top, #FDA251, #FB8F3D);\n"
"}\n"
"\n"
"QPushButton:orange:hover {\n"
"    border: 1px solid #EB5200;\n"
"    background: -webkit-linear-gradient(top, #FD924C, #F9760B); \n"
"    background: -moz-linear-gradient(top, #FD924C, #F9760B); \n"
"    background: -ms-linear-gradient(top, #FD924C, #F9760B); \n"
"    box-shadow: 0 1px #EFEFEF;\n"
"}\n"
"\n"
"QPushButton:orange:active {\n"
"    box-shadow: inset 0 1px 1px rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"/* Red Google Button as seen on drive.google.com */\n"
"QPushButton:red {\n"
"    background: -webkit-linear-gradient(top, #DD4B39, #D14836); \n"
"    background: -moz-linear-gradient(top, #DD4B39, #D14836); \n"
"    background: -ms-linear-gradient(top, #DD4B39, #D14836); \n"
"    border: 1px solid #DD4B39;\n"
"    color: white;\n"
"    text-shadow: 0 1px 0 #C04131;\n"
"}\n"
"\n"
"QPushButton:red:hover {\n"
"     background: -webkit-linear-gradient(top, #DD4B39, #C53727);\n"
"     background: -moz-linear-gradient(top, #DD4B39, #C53727);\n"
"     background: -ms-linear-gradient(top, #DD4B39, #C53727);\n"
"     border: 1px solid #AF301F;\n"
"}\n"
"\n"
"QPushButton:red:active {\n"
"     box-shadow: inset 0 1px 1px rgba(0,0,0,0.2);\n"
"    background: -webkit-linear-gradient(top, #D74736, #AD2719);\n"
"    background: -moz-linear-gradient(top, #D74736, #AD2719);\n"
"    background: -ms-linear-gradient(top, #D74736, #AD2719);\n"
"}\n"
"\n"
"\n"
"\n"
"/*=======================================*/\n"
"\n"
"body {\n"
"    margin: 50px;\n"
"}\n"
"\n"
"h1 {\n"
"    font: 150%/150% \'Freckle Face\', cursive;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    color: #444444;\n"
"    background: #F3F3F3;\n"
"    border: 1px #DADADA solid;\n"
"    padding: 5px 10px;\n"
"    border-radius: 2px;\n"
"    font-weight: bold;\n"
"    font-size: 9pt;\n"
"    outline: none;\n"
"}\n"
"\n"
"button:hover {\n"
"    border: 1px #C6C6C6 solid;\n"
"    box-shadow: 1px 1px 1px #EAEAEA;\n"
"    color: #333333;\n"
"    background: #F7F7F7;\n"
"}\n"
"\n"
"QPushButton:active {\n"
"    box-shadow: inset 1px 1px 1px #DFDFDF;   \n"
"}\n"
"\n"
"/* Blue button as seen on translate.google.com*/\n"
"QPushButton:blue {\n"
"    color: white;\n"
"    background: #4C8FFB;\n"
"    border: 1px #3079ED solid;\n"
"    box-shadow: inset 0 1px 0 #80B0FB;\n"
"}\n"
"\n"
"QPushButton:blue:hover {\n"
"    border: 1px #2F5BB7 solid;\n"
"    box-shadow: 0 1px 1px #EAEAEA, inset 0 1px 0 #5A94F1;\n"
"    background: #3F83F1;\n"
"}\n"
"\n"
"QPushButton:blue:active {\n"
"    box-shadow: inset 0 2px 5px #2370FE;   \n"
"}\n"
"\n"
"/* Orange button as seen on blogger.com*/\n"
"QPushButton:orange {\n"
"    color: white;\n"
"    border: 1px solid #FB8F3D; \n"
"    background: -webkit-linear-gradient(top, #FDA251, #FB8F3D);\n"
"    background: -moz-linear-gradient(top, #FDA251, #FB8F3D);\n"
"    background: -ms-linear-gradient(top, #FDA251, #FB8F3D);\n"
"}\n"
"\n"
"QPushButton:orange:hover {\n"
"    border: 1px solid #EB5200;\n"
"    background: -webkit-linear-gradient(top, #FD924C, #F9760B); \n"
"    background: -moz-linear-gradient(top, #FD924C, #F9760B); \n"
"    background: -ms-linear-gradient(top, #FD924C, #F9760B); \n"
"    box-shadow: 0 1px #EFEFEF;\n"
"}\n"
"\n"
"QPushButton:orange:active {\n"
"    box-shadow: inset 0 1px 1px rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"/* Red Google Button as seen on drive.google.com */\n"
"QPushButton:red {\n"
"    background: -webkit-linear-gradient(top, #DD4B39, #D14836); \n"
"    background: -moz-linear-gradient(top, #DD4B39, #D14836); \n"
"    background: -ms-linear-gradient(top, #DD4B39, #D14836); \n"
"    border: 1px solid #DD4B39;\n"
"    color: white;\n"
"    text-shadow: 0 1px 0 #C04131;\n"
"}\n"
"\n"
"QPushButton:red:hover {\n"
"     background: -webkit-linear-gradient(top, #DD4B39, #C53727);\n"
"     background: -moz-linear-gradient(top, #DD4B39, #C53727);\n"
"     background: -ms-linear-gradient(top, #DD4B39, #C53727);\n"
"     border: 1px solid #AF301F;\n"
"}\n"
"\n"
"QPushButton:red:active {\n"
"     box-shadow: inset 0 1px 1px rgba(0,0,0,0.2);\n"
"    background: -webkit-linear-gradient(top, #D74736, #AD2719);\n"
"    background: -moz-linear-gradient(top, #D74736, #AD2719);\n"
"    background: -ms-linear-gradient(top, #D74736, #AD2719);\n"
"}\n"
"\n"
"\n"
"\n"
"/*=======================================*/\n"
"\n"
"body {\n"
"    margin: 50px;\n"
"}\n"
"\n"
"h1 {\n"
"    font: 150%/150% \'Freckle Face\', cursive;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 3, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    color: #444444;\n"
"    background: #F3F3F3;\n"
"    border: 1px #DADADA solid;\n"
"    padding: 5px 10px;\n"
"    border-radius: 2px;\n"
"    font-weight: bold;\n"
"    font-size: 9pt;\n"
"    outline: none;\n"
"}\n"
"\n"
"button:hover {\n"
"    border: 1px #C6C6C6 solid;\n"
"    box-shadow: 1px 1px 1px #EAEAEA;\n"
"    color: #333333;\n"
"    background: #F7F7F7;\n"
"}\n"
"\n"
"QPushButton:active {\n"
"    box-shadow: inset 1px 1px 1px #DFDFDF;   \n"
"}\n"
"\n"
"/* Blue button as seen on translate.google.com*/\n"
"QPushButton:blue {\n"
"    color: white;\n"
"    background: #4C8FFB;\n"
"    border: 1px #3079ED solid;\n"
"    box-shadow: inset 0 1px 0 #80B0FB;\n"
"}\n"
"\n"
"QPushButton:blue:hover {\n"
"    border: 1px #2F5BB7 solid;\n"
"    box-shadow: 0 1px 1px #EAEAEA, inset 0 1px 0 #5A94F1;\n"
"    background: #3F83F1;\n"
"}\n"
"\n"
"QPushButton:blue:active {\n"
"    box-shadow: inset 0 2px 5px #2370FE;   \n"
"}\n"
"\n"
"/* Orange button as seen on blogger.com*/\n"
"QPushButton:orange {\n"
"    color: white;\n"
"    border: 1px solid #FB8F3D; \n"
"    background: -webkit-linear-gradient(top, #FDA251, #FB8F3D);\n"
"    background: -moz-linear-gradient(top, #FDA251, #FB8F3D);\n"
"    background: -ms-linear-gradient(top, #FDA251, #FB8F3D);\n"
"}\n"
"\n"
"QPushButton:orange:hover {\n"
"    border: 1px solid #EB5200;\n"
"    background: -webkit-linear-gradient(top, #FD924C, #F9760B); \n"
"    background: -moz-linear-gradient(top, #FD924C, #F9760B); \n"
"    background: -ms-linear-gradient(top, #FD924C, #F9760B); \n"
"    box-shadow: 0 1px #EFEFEF;\n"
"}\n"
"\n"
"QPushButton:orange:active {\n"
"    box-shadow: inset 0 1px 1px rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"/* Red Google Button as seen on drive.google.com */\n"
"QPushButton:red {\n"
"    background: -webkit-linear-gradient(top, #DD4B39, #D14836); \n"
"    background: -moz-linear-gradient(top, #DD4B39, #D14836); \n"
"    background: -ms-linear-gradient(top, #DD4B39, #D14836); \n"
"    border: 1px solid #DD4B39;\n"
"    color: white;\n"
"    text-shadow: 0 1px 0 #C04131;\n"
"}\n"
"\n"
"QPushButton:red:hover {\n"
"     background: -webkit-linear-gradient(top, #DD4B39, #C53727);\n"
"     background: -moz-linear-gradient(top, #DD4B39, #C53727);\n"
"     background: -ms-linear-gradient(top, #DD4B39, #C53727);\n"
"     border: 1px solid #AF301F;\n"
"}\n"
"\n"
"QPushButton:red:active {\n"
"     box-shadow: inset 0 1px 1px rgba(0,0,0,0.2);\n"
"    background: -webkit-linear-gradient(top, #D74736, #AD2719);\n"
"    background: -moz-linear-gradient(top, #D74736, #AD2719);\n"
"    background: -ms-linear-gradient(top, #D74736, #AD2719);\n"
"}\n"
"\n"
"\n"
"\n"
"/*=======================================*/\n"
"\n"
"body {\n"
"    margin: 50px;\n"
"}\n"
"\n"
"h1 {\n"
"    font: 150%/150% \'Freckle Face\', cursive;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 7, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Anime Sign&Song Creater"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "1"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "File Names"))
        self.pushButton_6.setText(_translate("MainWindow", "Tag to Keep"))
        self.pushButton_3.setText(_translate("MainWindow", "Remove Selected"))
        self.pushButton_7.setText(_translate("MainWindow", "Tag to Remove"))
        self.pushButton_2.setText(_translate("MainWindow", "Add Folder"))
        self.pushButton.setText(_translate("MainWindow", "Add Files"))
        self.pushButton_5.setText(_translate("MainWindow", "Start Ripping"))
        self.pushButton_4.setText(_translate("MainWindow", "Setting"))
